import "./globals.css";
import Layout from "@/lib/layout/Index";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
